### ISSUE TITLE
Explore button may result in 404 in first few minutes of being live

### ISSUE THREAD

**Issue by kal** [NetworkedPlanet/datadock#23]
GitHub pages takes a couple of minutes to update after the job has completed successfully, so the explore button can result in 404 at that point.

Is there a clean way to handle this? We have no control over the time delay for the GitHub Pages to update.

**Comment by kal** [comment]
Maybe just note this in an FAQ?

**Comment by jennet** [comment]
duplicate https://github.com/DataDock/datadock/issues/36
