### ISSUE TITLE
Import job listed as failed but is in github and on portal

### ISSUE THREAD

**Issue by kal** [NetworkedPlanet/datadock#43]
Uploaded a dataset which said it was failed but it's showing ok my portal and listed as a successful checkin on my github account

Job failed to attach the gzipped ntriples file to the release in GitHub. Unfortunately there is no further detail in the logs about why that happened. We probably need to start with adding more logging in that bit of the code if the attachment fails.

In any case, if the job does fail at this point we should really bubble up the error and not treat the dataset as successfully created.

**Comment by jennet** [comment]
moved https://github.com/DataDock/datadock/issues/66
