### ISSUE TITLE
Use HTTPS for all connections

### ISSUE THREAD

**Issue by bencomp** [NetworkedPlanet/datadock#52]
As a (potential) user, I expect to be redirected from <http://datadock.io> to <https://datadock.io>. When asked to sign up or log in over an (unencrypted) HTTP connection, I lose trust in the service.

Please setup TLS for all connections.

**Comment by jennet** [comment]
@bencomp We do indeed have this on our todo list too, we'll get that sorted ASAP ( we are looking into the best way to use TLS on both datadock.io and manage.datadock.io, all authentication itself is handled by github )

**Comment by kal** [comment]
Datadock now uses HTTPS for both the main datadock.io domain and the manage.datadock.io subdomain. 
HTTP connections are automatically redirected to HTTPS.
